Repository Ca2sta/oewoboka, pull requests merged in 2023-10, with the labels that each got.

#20 Quiz 페이지 UI 구현 & BottomSheetViewController 클래스 생성
  oewoboka/oewoboka.xcodeproj/project.pbxproj
  oewoboka/oewoboka/Enum/QuizResultType.swift
  oewoboka/oewoboka/Enum/QuizType.swift
  oewoboka/oewoboka/Helper/BottomSheetViewController.swift
  oewoboka/oewoboka/Resource/SceneDelegate.swift
  oewoboka/oewoboka/Scenes/AnswerPage/AnswerViewController.swift
  oewoboka/oewoboka/Scenes/AnswerPage/BottomSheetPresentationController.swift
  oewoboka/oewoboka/Scenes/AnswerPage/Cell/AnswerTableViewCell.swift
  oewoboka/oewoboka/Scenes/AnswerPage/View/BottomView.swift
  oewoboka/oewoboka/Scenes/AnswerPage/View/TopView.swift
  oewoboka/oewoboka/Scenes/QuizCompletePage/QuizCompleteViewController.swift
  oewoboka/oewoboka/Scenes/QuizCompletePage/View/FeedBackStackView.swift
  oewoboka/oewoboka/Scenes/QuizCompletePage/View/ResultView.swift
  oewoboka/oewoboka/Scenes/QuizPage/Model/Vocabulary.swift
  oewoboka/oewoboka/Scenes/QuizPage/Model/Word.swift
  oewoboka/oewoboka/Scenes/QuizPage/QuizViewController.swift
  oewoboka/oewoboka/Scenes/QuizPage/View/CardView.swift
  oewoboka/oewoboka/Scenes/QuizPage/View/QuizControlStackView.swift
  oewoboka/oewoboka/View/DefaultButton.swift
Labels: UI

#23 #2
  oewoboka/oewoboka.xcodeproj/project.pbxproj
  oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/FTOPViewController.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/FTOPViewModel.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/Views/FTModalBottomView.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/Views/FTModalMiddleView.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/Views/FTModalTopView.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/Views/FTSettingTypeCell.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/Views/QuizCountView.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/Views/QuizSettingView.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FTPage/FeatureViewController.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FTPage/Models/FeatureCellModels.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FTPage/Models/FeatureViewModel.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FTPage/Views/FeatureCollectionViewCell.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FeatureCollectionViewCell.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FeatureViewModel.swift
  oewoboka/oewoboka/Scenes/FeaturePage/Protocols/Protocol.swift
  oewoboka/oewoboka/Scenes/FeaturePage/VocaListSelectedPage/VocaListSelectedController.swift
  oewoboka/oewoboka/Scenes/PresentationController.swift
Labels: UI

#33 CoreData로 CRUD 기능 추가 + Quiz 페이지 Feature 페이지 화면 연결
  oewoboka/oewoboka.xcodeproj/project.pbxproj
  oewoboka/oewoboka/Model/Model.xcdatamodeld/Model.xcdatamodel/contents
  oewoboka/oewoboka/Model/VocabularyRepository.swift
  oewoboka/oewoboka/Scenes/AnswerPage/AnswerViewController.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/FTOPViewController.swift
  oewoboka/oewoboka/Scenes/FeaturePage/Models.swift
  oewoboka/oewoboka/Scenes/QuizCompletePage/QuizCompleteViewController.swift
  oewoboka/oewoboka/Scenes/QuizPage/Model/Vocabulary.swift
  oewoboka/oewoboka/Scenes/QuizPage/Model/Word.swift
  oewoboka/oewoboka/Scenes/QuizPage/QuizViewController.swift
Labels: FEAT

#37 [feat]추가하기UI구현
  oewoboka/oewoboka.xcodeproj/project.pbxproj
  oewoboka/oewoboka/Scenes/AddVocabularyPage/AddVocabularyViewController.swift
  oewoboka/oewoboka/Scenes/AddVocabularyPage/VocabularyViewController.swift
  oewoboka/oewoboka/Scenes/TabBarController.swift
Labels: UI

#40 [Feat] 추가하기 화면 UI 구현
  oewoboka/oewoboka.xcodeproj/project.pbxproj
  oewoboka/oewoboka/Helper/BottomSheetViewController.swift
  oewoboka/oewoboka/Model/VocabularyRepository.swift
  oewoboka/oewoboka/Scenes/AddVocabularyPage/AddVocabularyViewController.swift
  oewoboka/oewoboka/Scenes/AddVocabularyPage/AddWordViewController.swift
  oewoboka/oewoboka/Scenes/AddVocabularyPage/SelectVocabularyPage/BottomSheetSelectVocabularyViewController.swift
  oewoboka/oewoboka/Scenes/AddVocabularyPage/SelectVocabularyPage/Cell/VocabularyTableViewCell.swift
  oewoboka/oewoboka/Scenes/AddVocabularyPage/View/SelectVocabularyButton.swift
  oewoboka/oewoboka/Scenes/AddVocabularyPage/View/WordSaveNotificationView.swift
  oewoboka/oewoboka/Scenes/AddVocabularyPage/VocabularyViewController.swift
  oewoboka/oewoboka/Scenes/AnswerPage/AnswerViewController.swift
  oewoboka/oewoboka/Scenes/QuizCompletePage/QuizCompleteViewController.swift
Labels: UI

#41 [BUG] BottomSheetViewController로 닫기 기능이 안되는 버그 해결
  oewoboka/oewoboka.xcodeproj/project.pbxproj
  oewoboka/oewoboka/Helper/BottomSheetViewController.swift
  oewoboka/oewoboka/Scenes/AddVocabularyPage/SelectVocabularyPage/BottomSheetSelectVocabularyViewController.swift
  oewoboka/oewoboka/Scenes/AnswerPage/AnswerViewController.swift
  oewoboka/oewoboka/Scenes/AnswerPage/BottomSheetPresentationController.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/FTOPViewController.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FTPage/FeatureViewController.swift
  oewoboka/oewoboka/Scenes/VocaListPage/VocaListViewController.swift
Labels: BUG

#44 [FEAT] 받아쓰기 기능 추가
  oewoboka/oewoboka.xcodeproj/project.pbxproj
  oewoboka/oewoboka/Helper/BottomSheetViewController.swift
  oewoboka/oewoboka/Model/Model.xcdatamodeld/Model.xcdatamodel/contents
  oewoboka/oewoboka/Model/VocabularyEntity+CoreDataClass.swift
  oewoboka/oewoboka/Model/VocabularyEntity+CoreDataProperties.swift
  oewoboka/oewoboka/Model/VocabularyRepository.swift
  oewoboka/oewoboka/Scenes/QuizCompletePage/QuizCompleteViewController.swift
  oewoboka/oewoboka/Scenes/QuizPage/QuizViewController.swift
  oewoboka/oewoboka/Scenes/QuizPage/View/CardView.swift
  oewoboka/oewoboka/Scenes/VocaListPage/VocaListViewController.swift
Labels: FEAT

#53 [BUG] QuizPage 들어갈때 단어장 선택 안하면 아무것도 안보이는 버그 수정
  oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/FTOPViewController.swift
  oewoboka/oewoboka/Scenes/QuizPage/QuizViewController.swift
  oewoboka/oewoboka/Scenes/QuizPage/View/CardView.swift
  oewoboka/oewoboka/View/DefaultButton.swift
Labels: BUG

#58 [feat] CircleProgressBar 이니셜라이저에 rate 제거
  oewoboka/oewoboka.xcodeproj/project.pbxproj
  oewoboka/oewoboka/Scenes/QuizCompletePage/QuizCompleteViewController.swift
  oewoboka/oewoboka/Scenes/VocaListPage/VocaListTableViewCell.swift
  oewoboka/oewoboka/View/CircleProgressBar.swift
Labels: FEAT

#59 [BUG] BottomSheetViewController 상단 클릭하거나 조금만 드래그 한 경우 최상단으로 이동하는 버그 수정
  oewoboka/oewoboka/Helper/BottomSheetViewController.swift
Labels: BUG

#62 [BUG] 퀴즈 결과 화면에서 뒤로가기시 기능 선택 화면이 아니라 퀴즈화면으로 넘어가는 버그 수정
  oewoboka/oewoboka/Scenes/QuizCompletePage/QuizCompleteViewController.swift
Labels: BUG

#68 [FEAT]시간을 설정하고 시험을 테스트를 보듯 하는 기능 추가
  oewoboka/oewoboka.xcodeproj/project.pbxproj
  oewoboka/oewoboka/Extenstions/Int.swift
  oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/FTOPViewController.swift
  oewoboka/oewoboka/Scenes/QuizCompletePage/QuizCompleteViewController.swift
  oewoboka/oewoboka/Scenes/QuizCompletePage/View/FeedBackStackView.swift
  oewoboka/oewoboka/Scenes/QuizPage/QuizViewController.swift
  oewoboka/oewoboka/Scenes/QuizPage/QuziViewModel.swift
  oewoboka/oewoboka/Scenes/QuizPage/View/TimerSettingView.swift
  oewoboka/oewoboka/View/CircleProgressBar.swift
Labels: FEAT

#72 [Refactor] mvvm 패턴으로 리펙토링
  oewoboka/oewoboka/Scenes/QuizCompletePage/QuizCompleteViewController.swift
  oewoboka/oewoboka/Scenes/QuizCompletePage/View/FeedBackStackView.swift
  oewoboka/oewoboka/Scenes/QuizPage/QuizViewController.swift
  oewoboka/oewoboka/Scenes/QuizPage/QuziViewModel.swift
  oewoboka/oewoboka/Scenes/QuizPage/View/CardView.swift
  oewoboka/oewoboka/Scenes/QuizPage/View/QuizControlStackView.swift
Labels: REFACTOR

#73 [Fix] QuizPage UI 수정 + CardView 아래쪽 버튼 클릭 이벤트 추가 + 갯수 제한 기능
  oewoboka/oewoboka/Scenes/QuizPage/QuizViewController.swift
  oewoboka/oewoboka/Scenes/QuizPage/QuziViewModel.swift
  oewoboka/oewoboka/Scenes/QuizPage/View/CardView.swift
  oewoboka/oewoboka/Scenes/QuizPage/View/QuizControlStackView.swift
Labels: FEAT, UI

#75 [BUG] 단어를 생성하지 않고 +버튼만 누르고 나와도 단어 갯수가 증가하는 버그 수정
  oewoboka/oewoboka/Scenes/VocaListPage/VocaViewController.swift
Labels: BUG

#76 [FEAT] 단어장 삭제 기능 추가
  oewoboka/oewoboka/Scenes/VocaListPage/VocaListTableViewCell.swift
  oewoboka/oewoboka/Scenes/VocaListPage/VocaListViewController.swift
Labels: FEAT
